apiVersion: apps/v1
kind: Deployment
metadata:
  name: funnynames-deployment
  namespace: funny
spec:
  replicas: 3  # Adjust the number of replicas as needed
  selector:
    matchLabels:
      app: funnynames
  template:
    metadata:
      labels:
        app: funnynames
    spec:
      containers:
      - name: funnynames
        image: funnynames:1.0.0
        ports:
        - containerPort: 5000
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 200m
            memory: 256Mi
        env:
          - name: MYNAME
            value: saai
---
apiVersion: v1
kind: Service
metadata:
  name: funnynames-service
  namespace: funny
spec:
  selector:
    app: funnynames
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
