apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}-deployment
  namespace: {{ .Values.appNameSpace }}
spec:
  replicas: {{ .Values.deployment.replicaCount }}  # Adjust the number of replicas as needed
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      containers:
      - name: {{ .Values.appName }}
        image: {{ .Values.deployment.imageName }}:{{ .Values.deployment.imageVersion }}
        ports:
        - containerPort: {{ .Values.deployment.containerPort }}
        resources:
            {{- toYaml .Values.resources | nindent 12 }}
        env:
          - name: {{ .Values.env.MYNAME.name }}
            value: {{ .Values.env.MYNAME.value }}