apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}-service
  namespace: {{ .Values.appNameSpace }}
spec:
  selector:
    app: {{ .Values.appName }}
  ports:
    - protocol: {{ .Values.service.ports.serviceProtocol }}
      port: {{ .Values.service.ports.servicePort }}
      targetPort: {{ .Values.service.ports.targetPort }}